training:
  algo: sliced
  n_epochs: 3000
  batch_size: 50
  fval_batch_size: 50
  patience: 500

data:
  dataset: Seizure
  input_dim: 178

model:
  M: 50
  num_kernels: 3
  hidden_dim: 128
  num_layers: 4
  add_skip: True
  alpha_param: False       
  train_Z: True
  
optim:
  optimizer: Adam
  lr: 0.0001
  weight_decay: 0.0