training:
  algo: sliced_VR
  n_epochs: 3000
  batch_size: 128
  fval_batch_size: 128
  patience: 200
  sampling_batch_size: 1000
  
data:
  dataset: Synthetic1000
  input_dim: 1000
  scaler: pca_whiten

model:
  M: 200
  num_kernels: 4
  hidden_dim: 64
  num_layers: 3
  add_skip: True
  alpha_param: False       
  train_Z: True
  
optim:
  optimizer: Adam
  lr: 0.01
  weight_decay: 0.0