training:
  algo: sliced
  n_epochs: 1000
  batch_size: 50
  fval_batch_size: 50
  patience: 200

data:
  dataset: Wifi
  input_dim: 300

model:
  M: 50
  num_kernels: 5
  hidden_dim: 64
  num_layers: 5
  add_skip: True
  alpha_param: False
  train_Z: True

optim:
  optimizer: Adam
  lr: 0.0001
  weight_decay: 0.0
